name: Build

on:
  release:
    types: [published]
  schedule:
    - cron: "0 * * * 1-4"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install requests
      run: pip install requests
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: | 
        cp ${{ github.workspace }}/run/test.py ${{ github.workspace }}/run.py
        echo $CONFIG_ID > config_id.txt
        echo $CONFIG_KEY > config_key.txt
        sed -i '10 r config_id.txt' run.py
        sed -i '12 r config_key.txt' run.py
    - name: Build
      run: | 
        python run.py
