name: Build

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: "0 * * * 1-4"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install requests
      run: pip install requests
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: | 
        cp test.py run.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '10 r configid.txt' run.py
        sed -i '12 r configkey.txt' run.py
    - name: Build
      run: | 
        python run.py
