name: Update

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "50 * * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: pip install requests
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: | 
        # Copy the original script and append the config values
        cp update.py update2.py
        echo "config_id = $CONFIG_ID" >> update2.py
        echo "config_key = $CONFIG_KEY" >> update2.py
    - name: Update token
      run: python update2.py
    - name: Delete secrets config
      run: | 
        # Remove the temporary files
        rm -f update2.py
        rm -f configid.txt
        rm -f configkey.txt 
    - name: Commit
      run: |
        # Set the user name and email for git
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name AutoupdateRobot
        # Add and commit the changes
        git add .
        git commit -m "follow taffy thanks nya" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
