name: Update

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: "50 * * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install requests
      run: pip install requests
    - name: Install rsa
      run: pip install rsa
    - name: Read config from secrets
      run: | 
        cp update.py updater.py
        echo "${{ secrets.CONFIG_ID }}" > configid.txt
        sed -i '6 r configid.txt' updater.py
        echo "${{ secrets.CONFIG_KEY }}" > configkey.txt
        sed -i '8 r configkey.txt' updater.py
        echo "${{ secrets.P_KEY }}" | sed 's/\\n/\n/g' > public_key.txt
        
    - name: Update token
      run: python updater.py
    - name: Delete secrets config
      run: | 
        rm -f updater.py
        rm -f configid.txt
        rm -f configkey.txt 
    - name: Commit
      run: |
        git config --global user.email EpicTeamAdmin@users.noreply.github.com
        git config --global user.name EpicTeamAdmin
        git add .
        git commit -m "Follow taffy, thanks, nya~" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
